version: '3.7'
services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: chart_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_chart
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: